apiVersion: v1
kind: Service
metadata:
  name: ubuntu-xfce-vnc
  namespace: ubuntu-xfce
spec:
  type: NodePort
  selector:
    app: ubuntu-xfce-vnc
  ports:
  - name: vnc
    protocol: TCP
    port: 5901
    targetPort: 5901
    nodePort: 30901
  - name: web-vnc
    protocol: TCP
    port: 6901
    targetPort: 6901
    nodePort: 30902
